#nome da aplicacao:
spring.application.name=taskList

#ambiente de teste:
spring.profiles.active=test 

#A sessão com o banco continua aberta depois que o serviço terminou;
#Permite carregar dados lazy (carregamento preguiçoso) mesmo fora do service;
spring.jpa.open-in-view=true